title: Nostr Guide
description: A beginner-friendly guide to Nostr
theme: just-the-docs

aux_links:
  View on GitHub: https://github.com/swiftsats/nostr_guide

# Optional: logo, favicon, or color customization could be added here later
